config/routes.rb
Jevoudrais::Application.routes.draw do

  resources :gift_templates
  resources :gifts
  resources :events

  get '/about' => 'home#about'
  get '/gift_creator' => 'home#gift_creator'
  post '/give' => 'gifts#give'
  get '/get_giver/:id' => 'gifts#get_giver'
  post '/remove_gift' => 'gifts#remove_gift'
  put '/notifications/:id' => 'notifications#update'
  get '/search' => 'home#search'

  devise_for :gift_creators, :controllers => { :registrations => "gift_creators/registrations" }

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, :skip => [:sessions, :registration]

  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end

  authenticated :user do
    root :to => 'home#index', as: 'logged_in'
  end

  root :to => 'home#new', as: 'root'
end

app/models/gift_template.rb
class GiftTemplate < ActiveRecord::Base
  belongs_to :gift_creator
  has_many :clicks
  attr_accessible :image_link, :name, :product_link, :gift_creator_id

  def self.get_gift_template(id)
    GiftTemplate.find(id)
  end
end

app/controllers/gift_templates_controller.rb
class GiftTemplatesController < ApplicationController
  # GET /gift_templates
  # GET /gift_templates.json
  def index
    @gift_templates = current_gift_creator.gift_templates

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gift_templates }
    end
  end

  # GET /gift_templates/1
  # GET /gift_templates/1.json
  def show
    @gift_template = GiftTemplate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gift_template }
    end
  end

  # GET /gift_templates/new
  # GET /gift_templates/new.json
  def new
    @gift_template = GiftTemplate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gift_template }
    end
  end

  # GET /gift_templates/1/edit
  def edit
    @gift_template = GiftTemplate.find(params[:id])
  end

  # POST /gift_templates
  # POST /gift_templates.json
  def create
    @gift_template = GiftTemplate.new(params[:gift_template])

    respond_to do |format|
      if @gift_template.save
        format.html { redirect_to gift_templates_path, notice: 'Gift template was successfully created.' }
        format.json { render json: @gift_template, status: :created, location: @gift_template }
      else
        format.html { render action: "new" }
        format.json { render json: @gift_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /gift_templates/1
  # PUT /gift_templates/1.json
  def update
    @gift_template = GiftTemplate.find(params[:id])

    respond_to do |format|
      if @gift_template.update_attributes(params[:gift_template])
        format.html { redirect_to gift_templates_path, notice: 'Gift template was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gift_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gift_templates/1
  # DELETE /gift_templates/1.json
  def destroy
    @gift_template = GiftTemplate.find(params[:id])
    @gift_template.destroy

    respond_to do |format|
      format.html { redirect_to gift_templates_path }
      format.json { head :no_content }
    end
  end
end

app/helpers/gift_templates_helper.rb
module GiftTemplatesHelper
end

app/views/gift_templates/_form.html.erb
<%= simple_form_for(@gift_template) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :image_link %>
    <%= f.input :product_link %>
    <%= f.input :gift_creator_id, :as => :hidden, :input_html => { :value => current_gift_creator.id } %>
  </div>

  <%= f.button :submit, "Create" %>
<% end %>

app/views/gift_templates/edit.html.erb
<h1>Editing gift_template</h1>

<%= render 'form' %>

<%= link_to 'Show', @gift_template %> |
<%= link_to 'Back', gift_templates_path %>

app/views/gift_templates/index.html.erb
<div class="jevoudrais-table-header">
<h2>Your gift templates</h2>
</div>
<br />

<%= link_to "New template", new_gift_template_path, :class => "btn pull-right" %>
<br />
<br />
<table class="table table-hover">
  <tr>
    <th>Name</th>
    <th>Image link</th>
    <th>Product link</th>
    <th></th>
    <th></th>
  </tr>

<% @gift_templates.each do |gift_template| %>
  <tr>
    <td><%= link_to gift_template.name, gift_template %></td>
    <td><%= gift_template.image_link %></td>
    <td><%= link_to gift_template.product_link, gift_template.product_link %></td>
    <td><%= link_to 'Edit', edit_gift_template_path(gift_template), :class => "btn btn-mini" %></td>
    <td><%= link_to 'Remove', gift_template, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-mini" %></td>
  </tr>
<% end %>
</table>

app/views/gift_templates/new.html.erb
<div class="jevoudrais-table-header">
	<h2>Create new gift template</h2>
</div>
<br />
<%= render 'form' %>

app/views/gift_templates/show.html.erb
<div class="jevoudrais-table-header">
	<h2><%= @gift_template.name %></h2>
</div>
<br />
<div class="row-fluid">
	<div class="span4">
		<p>
		  <%= link_to @gift_template.product_link, @gift_template.product_link %>
		</p>
		<br />
		<br />
		<%= link_to 'Edit', edit_gift_template_path(@gift_template), :class => "btn" %>
	</div>
	
	<div class="span8">
		<%= image_tag @gift_template.image_link, :alt => @gift_template.name %>
	</div>

</div>