config/routes.rb
Jevoudrais::Application.routes.draw do

  resources :gift_templates
  resources :gifts
  resources :events

  get '/about' => 'home#about'
  get '/gift_creator' => 'home#gift_creator'
  post '/give' => 'gifts#give'
  get '/get_giver/:id' => 'gifts#get_giver'
  post '/remove_gift' => 'gifts#remove_gift'
  put '/notifications/:id' => 'notifications#update'
  get '/search' => 'home#search'

  devise_for :gift_creators, :controllers => { :registrations => "gift_creators/registrations" }

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, :skip => [:sessions, :registration]

  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end

  authenticated :user do
    root :to => 'home#index', as: 'logged_in'
  end

  root :to => 'home#new', as: 'root'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @gifts = current_user.gifts
    @notifications = current_user.notifications.where(:seen => false)
    # caching for 30 minutes
    if ((current_user.cache_time + 30.minutes) < DateTime.now) or current_user.cached_friends.empty?
      token = current_user.token
      user = FbGraph::User.me(token)
      @friends = user.friends
      @friends.collect!{ |friend| friend.identifier }
      @users = User.where(:uid => @friends)
      current_user.update_attributes(:cached_friends => @users.collect { |user| user.id }.join(","), :cache_time => DateTime.now)
    else
      users_string = current_user.cached_friends.split(",")
      users_string.collect! { |user| user.to_i }
      @users = User.where(:id => users_string)
    end

    @own_events = current_user.events

    @events = []

    @users.each do |user|
      tmp_events = user.events

      tmp_events.each do |event|
        @events.push(event)
      end
    end

    @events.sort_by! { |e| e.event_date }
  end

  def new

  end

  def search
    string = params[:query]
    @templates = GiftTemplate.where('name LIKE ?', "%#{string}%")

    @results = @templates.collect do |template|
      { id: template.id, name: template.name, photo: template.image_link }
    end

    respond_to do |format|
      format.json { render json: @results }
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="about-header">
	<h1>About</h1>
</div>	
<br /><br />
<p>a small simple wish list</p>

app/views/home/index.html.erb
<div class="span5 jevoudrais-table-header">
	<h2>Your wish list</h2>
	<table class="table">
		<tbody id="gifts">
			<% @gifts.each do |gift| %>
			<tr id="<%= gift.id %>">
				<td><%= gift.name %></td>
				<% if gift.user == current_user %>
					<td><%= link_to gift, :remote => true, :method => :delete, :id => "delete-gift", :title => "Remove gift" do %>
						<i class="icon-remove"></i>
					<% end %></td>
				<% end %>
			</tr>
			<% end %>
		</tbody>
	</table>

	<div class="input-append">
		<%= form_for Gift.new, :html => {:id => 'gift-form'},:remote => true do |f| %>
			<%= f.hidden_field :user_id, :value => current_user.id %>
			<%= f.hidden_field :gift_template_id, :id => 'hidden-gift-template' %>
			<%= f.text_field :name, :id => "gift-name", :class => "input-xlarge" %>
			<%= f.submit 'Add gift', :class => 'btn', :id => 'submit-button' %>
		<% end %>
	</div>
	<div id="error-text"></div>

	<br /><br />
	<h2>Your events</h2>
	<table class="table">
		<tbody id="events">
			<% @own_events.each do |event| %>
			<tr id="<%= event.id %>">
				<td><%= event.name %></td>
				<td><%= event.event_date %></td>
				<td><%= link_to event, :remote => true, :method => :delete, :id => "delete-event", :title => "Remove event	" do %>
					<i class="icon-remove"></i>
				<% end %></td>
			</tr>
			<% end %>
		</tbody>
	</table>

	<a href="#eventModal" role="button" class="btn pull-right" data-toggle="modal">New event</a>

	<!-- Modal -->
	<div id="eventModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	  <div class="jevoudrais-table-header modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	    <h2 id="myModalLabel">New event</h2>
	  </div>
	  <div class="modal-body">
	    <%= form_for(Event.new, :html => { :class => 'form-vertical', :id => 'events-form' } ) do |f| %>
				<div class="field">
					<p>Name of event:</p>
			  	<%= f.text_field :name, :autofocus => true %>
				</div>
				<br />
				<div class="field">
					<p>Date of event:</p>
			  	<%= f.text_field :event_date,  :id => 'datepicker' %>
				</div>
				<br />
				<div class="field">
					<p>Is the event recurring?&nbsp;</p>
					<%= f.check_box :recurring %>
				</div>


				<%= f.hidden_field :user_id, :value => current_user.id %><br />
	  </div>
	  <div class="modal-footer">
	    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
	    <%= f.submit 'Save event', :class => 'btn btn-primary' %>
	  </div>
		<% end %>
	</div>
</div>

<div class="span5 offset2 jevoudrais-table-header">
	<h2>Friends</h2>
	<table class="table">
		<tbody class="vert-align">
			<% @events.each do |event| %>
			<tr>
				<td><%= link_to image_tag(event.user.image_link, :alt => event.user.name), gifts_path(:user => event.user.id) %></td>
				<td><%= link_to event.user.name, gifts_path(:user => event.user.id) %></td>
				<td><%= event.name %></td>
				<td><%= event.event_date.strftime("%B %e") %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>


<div id="notificationModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Notifications</h3>
  </div>
  <div class="modal-body" id="modal-body">
    <% @notifications.each do |notification| %>
			<p id="<%= notification.id %>"><%= notification.body %></p>
		<% end %>
  </div>
</div>

app/views/home/new.html.erb
<br />
<br />
<br />
<br />
<div class="jevoudrais-header">
	<h1>jevoudrais</h1>
	<br />
	<br />
	<br />
	<br />
	<p><%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook), :'data-no-turbolink' => true %></p>
</div>

<div id="footer">
<p><%= link_to 'About', about_path %> | Created by <a href="http://olesennielsen.dk">Olesen & Nielsen</a> and <a href="http://www.ventiro.se">Ventiro AB</a></p>
</div>