config/routes.rb
Jevoudrais::Application.routes.draw do

  resources :gift_templates
  resources :gifts
  resources :events

  get '/about' => 'home#about'
  get '/gift_creator' => 'home#gift_creator'
  post '/give' => 'gifts#give'
  get '/get_giver/:id' => 'gifts#get_giver'
  post '/remove_gift' => 'gifts#remove_gift'
  put '/notifications/:id' => 'notifications#update'
  get '/search' => 'home#search'

  devise_for :gift_creators, :controllers => { :registrations => "gift_creators/registrations" }

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, :skip => [:sessions, :registration]

  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end

  authenticated :user do
    root :to => 'home#index', as: 'logged_in'
  end

  root :to => 'home#new', as: 'root'
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
	<% if name != :notice %>
		<% if msg.is_a?(String) %>
		<div class="alert alert-error">
			<a class="close" data-dismiss="alert">&#215;</a>
			<%= content_tag :div, msg, :id => "flash_#{name}" %>
		</div>
		<% end %>
	<% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<% if user_signed_in? %>
  <p class="pull-right">&nbsp;&nbsp;<%= link_to 'Logout', users_sign_out_path, :method=>'delete' %></p>
	<% if (params[:controller] == 'home' and params[:action] == 'index' ) %>
		<% unless @notifications.empty? %>
			<p id='notifications-link'><a href="#notificationModal" role="button" class="pull-right" data-toggle="modal"><%= @notifications.count %> notifications</a></p>
		<% end %>		
	<% else %>
		<p class="pull-right"><%= link_to 'Back', root_path, :'data-no-turbolink' => true %>&nbsp;&nbsp;</p>
	<% end %>
<% elsif gift_creator_signed_in? %>
	<p class="pull-right">&nbsp;&nbsp;<%= link_to 'Logout', destroy_gift_creator_session_path, :method=>'delete' %></p>
	<% unless (params[:controller] == 'gift_templates' and params[:action] == 'index' ) %>
		<p class="pull-right"><%= link_to 'Back', root_path, :'data-no-turbolink' => true %>&nbsp;&nbsp;</p>
	<% end %>
<% else %>
	<% unless (params[:controller] == 'home' and params[:action] == 'new' ) %>
		<p class="pull-right"><%= link_to 'Back', root_path, :'data-no-turbolink' => true %></p>
	<% end %>
<% end %>
<br />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "jevoudrais" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Jevoudrais" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div id="main" role="main">
      <div class="container" id="container">
           <div class="row">
            <div class="span12">
							<%= render 'layouts/navigation' %>
              <%= render 'layouts/messages' %>
            </div>
          </div>
					<div class="row-fluid">
						<%= yield %>	
					</div>	
          <footer>
          </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>